version: '2'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - .docker/data/db:/var/lib/mysql
    php:
        build: .docker/php-fpm
        ports:
            - "9001:9001"
        volumes:
            - .:/var/www/app
            - .docker/logs/symfony:/var/www/app/var/logs:cached
        links:
            - db
    nginx:
        build: .docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - .docker/logs/nginx:/var/log/nginx:cached

    redis:
      image: redis
      ports:
        - 6379:6379